# Generated by Django 3.1.1 on 2020-09-15 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhes',
            name='il',
        ),
        migrations.RemoveField(
            model_name='detalhes',
            name='sp',
        ),
        migrations.AddField(
            model_name='detalhes',
            name='opção',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalhes',
            name='tipo',
            field=models.CharField(default='nulo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoscursos',
            name='inicio',
            field=models.DateField(default=datetime.datetime(2020, 9, 15, 0, 3, 37, 27259, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
