# Generated by Django 3.1.1 on 2020-09-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200915_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoscursos',
            name='inicio',
        ),
    ]
